language: python
python:
  - "2.7"
  - "3.5"
services:
  - mysql
  - postgresql
addons:
  postgresql: "10"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - mysql -e 'CREATE DATABASE test;'
  - psql -c 'CREATE DATABASE test;' -U postgres
script:
  - python -m pytest
  - coverage run --source=ezrecords -m pytest
after_success: coveralls
