language: python
python:
  - "2.7"
  - "3.5"
services:
  - mysql
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - mysql -e 'CREATE DATABASE test;'
  - psql -c 'CREATE DATABASE test;' -U postgres
script:
  - python -m unittest discover -s tests
  - coverage run --source=ezrecords -m unittest discover -s tests
after_success: coveralls


